config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :users

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/links', to: 'static#main'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :links
    end
  end


end

app/models/link.rb
require 'uri'

class Link < ActiveRecord::Base
  belongs_to :user
  validates_format_of :url, :with=> URI::regexp(%w(http https))
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true,
                    uniqueness: true

  validates :password, confirmation: true

  has_many :links
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def index
    respond_with Link.all
  end

  def show
    respond_with Link.find(params[:id])
  end

  def create
    link = Link.new(link_params)
    if link.save
      respond_with(link, status: 201, location: api_v1_link_path(link))
    else
      render json: { errors: link.errors }, status: 422, location: api_v1_links_path
    end
  end

  def update
    link = Link.find(params[:id])
    if link.update(link_params)
      respond_with(link, status: 200, location: api_v1_link_path(link))
    else
      render json: link.errors, status: 422
    end
  end

  def destroy
    Link.find(params[:id]).destroy
    head :no_content
  end

  private

  def link_params
    params.permit(:link, :url, :title)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:error] = "Invalid password. Try again."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:logout] = "Goodbye!"
    redirect_to login_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def main
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{@user.email}"
      redirect_to links_path
    else
      flash.now[:error] = "Something went wrong. Please try again."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="welcome text-center">
  <p> Welcome to</p>
  <h1>THOUGHTBOX</h1>
  <%= link_to "Log In or Sign Up", login_path, class:"btn btn-primary" %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">THOUGHT BOX</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Logout", logout_path , method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughbox</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.0-beta.8/angular.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="Link">
  <div ="primary-navigation">
    <%= render partial: "layouts/navbar" %>
  </div>

  <% if flash[:success] %>
    <div id="nav-bar" class="green lighten-2 alert white-text">
    <p><%= raw(flash[:success]) %></p>
    </div>
  <% else %>
    <div id="nav-bar" class="custom-green lighten-2 alert white-text">
    <% flash.each do |type, message| %>
      <p><%= content_tag(:div, message) %></p>
    <% end %>
    </div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</body>
</html>

app/views/links/index.html.erb
<div class="text-center">

  <h1> <%= current_user.email %>'s Links</h1>
  <br>

  <%= form_for(Link.new) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit "Submit New Link", class:"btn btn-primary" %>
  <% end %>

  <br>

  <% @links.each do |link| %>
    <h3><%= link_to link.title, link.url %></h3>
    <%= link_to "Delete Link", link_path(link), method: :delete, class:"btn btn-danger" %>
  <% end %>
</div>

app/views/links/new.html.erb
<div class="text-center">

  <%= form_for(Link.new) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit "Submit New Link", class:"btn btn-primary" %>
  <% end %>

</div>

app/views/links/show.html.erb
<div class="text-center">

  <%= form_for(@link) do |f| %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit "Edit Link", class:"btn btn-primary", method: :update %>
  <% end %>

</div>

app/views/users/new.html.erb
<div class="signup-form">
  <%= form_for(@user) do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit "Create Account", class: "btn" %>
  <% end %>
</div>